"""Generated by Django 5.0.1 on 2022-06-15 11:07"""

from django.db import migrations, models


class Migration(migrations.Migration):
    """migration file for menu app"""

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
            ],
        ),
    ]
